/**
 * TwiML XML Escaping Validation Script
 * 
 * This script validates that all TwiML generated by the application:
 * 1. Is well-formed XML
 * 2. Contains properly escaped ampersands (&amp; not &)
 * 3. Callback URLs resolve correctly when parsed
 * 
 * This prevents Twilio application errors caused by unescaped ampersands
 * in callback URLs within XML attributes.
 * 
 * Run with: npx tsx src/lib/__tests__/twiml-xml-escaping.test.ts
 */

import VoiceResponse from 'twilio/lib/twiml/VoiceResponse'
import { buildCallbackUrl } from '@/lib/public-origin'

// Simple XML parser for Node.js environment
function parseXML(xmlString: string): Document {
  // In Node.js, we need to use a different approach for XML parsing
  // For now, we'll do basic validation with regex
  return xmlString as any
}

function assert(condition: boolean, message: string): void {
  if (!condition) {
    console.error(`❌ FAILED: ${message}`)
    process.exit(1)
  }
  console.log(`✓ ${message}`)
}

function testPersonalVoicemailTwiML(): void {
  console.log('\n=== Testing Personal Voicemail TwiML ===')
  
  const businessId = 'test-business-123'
  const callerPhone = '+1234567890'
  const voicemailMessage = "Thank you for calling. Please leave a message after the tone."
  
  // Build callback URLs using the canonical helper
  const actionUrl = buildCallbackUrl('/api/twilio/personal-voicemail', {
    businessId,
    callerPhone
  })
  
  const recordingStatusCallbackUrl = buildCallbackUrl('/api/twilio/recording-status', {
    businessId,
    callerPhone
  })
  
  // Generate TwiML using VoiceResponse builder
  const response = new VoiceResponse()
  response.pause({ length: 1 })
  response.say({ voice: "alice" }, voicemailMessage)
  response.record({
    maxLength: 60,
    playBeep: true,
    trim: "trim-silence",
    action: actionUrl,
    method: "POST",
    recordingStatusCallback: recordingStatusCallbackUrl,
    recordingStatusCallbackMethod: "POST",
  })
  response.hangup()
  
  const twiml = response.toString()
  
  console.log('Generated TwiML:', twiml)
  
  // Test 1: XML should contain Response root element
  assert(twiml.includes('<Response>'), 'XML contains Response root element')
  assert(twiml.includes('</Response>'), 'XML contains Response closing tag')
  
  // Test 2: XML should NOT contain unescaped ampersands
  // This is the critical test - if & appears in the raw XML without being escaped as &amp;, it will fail
  const unescapedAmpersandPattern = /&(?!(?:amp|lt|gt|quot|apos);)/
  const hasUnescapedAmpersand = unescapedAmpersandPattern.test(twiml)
  assert(!hasUnescapedAmpersand, 'XML does NOT contain unescaped ampersands')
  
  // Test 3: XML should contain properly escaped ampersands in callback URLs
  // The callback URLs should have &amp; separating query parameters
  assert(twiml.includes('&amp;'), 'XML contains escaped ampersands (&amp;)')
  assert(twiml.includes('&amp;businessId='), 'XML contains &amp;businessId=')
  assert(twiml.includes('&amp;callerPhone='), 'XML contains &amp;callerPhone=')
  
  // Test 4: Callback URLs should be on https://www.replyflowhq.com
  assert(actionUrl.startsWith('https://www.replyflowhq.com/'), 'Action URL is on https://www.replyflowhq.com')
  assert(recordingStatusCallbackUrl.startsWith('https://www.replyflowhq.com/'), 'RecordingStatusCallback URL is on https://www.replyflowhq.com')
  
  // Test 5: Callback URLs should contain the expected path
  assert(actionUrl.includes('/api/twilio/personal-voicemail'), 'Action URL contains correct path')
  assert(recordingStatusCallbackUrl.includes('/api/twilio/recording-status'), 'RecordingStatusCallback URL contains correct path')
  
  console.log('✅ Personal Voicemail TwiML tests passed')
}

function testStandardVoicemailTwiML(): void {
  console.log('\n=== Testing Standard Voicemail TwiML ===')
  
  const voicemailMessage = "Thank you for calling. We're sorry we missed your call. Please leave your name and the reason for your call after the tone, and we'll get back to you as soon as possible."
  
  const response = new VoiceResponse()
  response.pause({ length: 1 })
  response.say({ voice: "alice" }, voicemailMessage)
  response.record({
    maxLength: 60,
    playBeep: true,
    trim: "trim-silence",
    action: "/api/twilio/voicemail",
    method: "POST",
    recordingStatusCallback: "/api/twilio/recording-status",
    recordingStatusCallbackMethod: "POST",
  })
  response.hangup()
  
  const twiml = response.toString()
  
  console.log('Generated TwiML:', twiml)
  
  // Test: XML should be well-formed
  assert(twiml.includes('<Response>'), 'XML contains Response root element')
  assert(twiml.includes('</Response>'), 'XML contains Response closing tag')
  
  // Test: No unescaped ampersands (though this TwiML has no dynamic URLs)
  const unescapedAmpersandPattern = /&(?!(?:amp|lt|gt|quot|apos);)/
  const hasUnescapedAmpersand = unescapedAmpersandPattern.test(twiml)
  assert(!hasUnescapedAmpersand, 'XML does NOT contain unescaped ampersands')
  
  console.log('✅ Standard Voicemail TwiML tests passed')
}

function testIgnoredContactHangupTwiML(): void {
  console.log('\n=== Testing Ignored Contact Hangup TwiML ===')
  
  const response = new VoiceResponse()
  response.hangup()
  
  const twiml = response.toString()
  
  console.log('Generated TwiML:', twiml)
  
  // Test: XML should be well-formed
  assert(twiml.includes('<Response>'), 'XML contains Response root element')
  assert(twiml.includes('</Response>'), 'XML contains Response closing tag')
  assert(twiml.includes('<Hangup/>'), 'XML contains Hangup element')
  
  console.log('✅ Ignored Contact Hangup TwiML tests passed')
}

function testRedirectTwiML(): void {
  console.log('\n=== Testing Redirect TwiML ===')
  
  const response = new VoiceResponse()
  response.redirect('/api/twilio/voice')
  
  const twiml = response.toString()
  
  console.log('Generated TwiML:', twiml)
  
  // Test: XML should be well-formed
  assert(twiml.includes('<Response>'), 'XML contains Response root element')
  assert(twiml.includes('</Response>'), 'XML contains Response closing tag')
  assert(twiml.includes('<Redirect>'), 'XML contains Redirect element')
  
  console.log('✅ Redirect TwiML tests passed')
}

// Run all tests
console.log('🧪 Starting TwiML XML Escaping Validation Tests...\n')

try {
  testPersonalVoicemailTwiML()
  testStandardVoicemailTwiML()
  testIgnoredContactHangupTwiML()
  testRedirectTwiML()
  
  console.log('\n✅ All TwiML XML escaping tests passed!')
  console.log('\n✅ The TwiML is well-formed and contains properly escaped ampersands.')
  console.log('✅ Callback URLs are on https://www.replyflowhq.com')
  console.log('✅ No unescaped ampersands found in any TwiML output.')
  process.exit(0)
} catch (error) {
  console.error('\n❌ Test failed with error:', error)
  process.exit(1)
}
